#!/bin/bash
#SBATCH --partition=GPU
#SBATCH --job-name=cyGAN
#SBATCH --output=results.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=alejandro.lemus@cimat.mx
cd /home/est_posgrado_alejandro.lemus/DL2/Tarea2
source /opt/anaconda3_titan/bin/activate
conda activate Deep2
hostname
date
python3 cycleGAN.py
date
